import type { CandidateVessel, DashboardPayload, GeoCollection, PipelineStatus, ScenarioId } from '../types/domain';
const p=(coordinates:[number,number], properties:Record<string,unknown>={})=>({type:'Feature' as const,properties,geometry:{type:'Point' as const,coordinates}});
const l=(coordinates:[number,number][],properties:Record<string,unknown>={})=>({type:'Feature' as const,properties,geometry:{type:'LineString' as const,coordinates}});
const poly=(coordinates:[number,number][][],properties:Record<string,unknown>={})=>({type:'Feature' as const,properties,geometry:{type:'Polygon' as const,coordinates}});
const center:[number,number]=[65.42,15.21], origin:[number,number]=[65.18,15.12];
const stages=(s:ScenarioId)=>['Satellite','Detection','Characterisation','Environment','Hindcast','AIS','Attribution','Confidence','Forecast'].map((label,i)=>({id:label.toLowerCase(),label,status:(s==='processing'&&i===2?'running':s==='error'&&i===4?'failed':s==='no-oil'&&i>1?'unavailable':s==='no-environment'&&(i===3||i===4||i===8)?'unavailable':'complete') as PipelineStatus}));
export function dashboardScenario(scenario:ScenarioId='full'):DashboardPayload {
 const noOil=scenario==='no-oil', noEnv=scenario==='no-environment', noAis=scenario==='no-ais', partial=scenario==='partial-ais';
 const spillPolygon=poly([[[65.29,15.12],[65.47,15.08],[65.58,15.19],[65.49,15.31],[65.31,15.29],[65.29,15.12]]],{layer:'spill',title:'Detected spill'});
 const hindcast=l([center,[65.36,15.18],[65.27,15.15],origin],{layer:'hindcast',title:'Hindcast path'});
 const forecast=l([center,[65.54,15.29],[65.71,15.36],[65.89,15.42]],{layer:'forecast',title:'Forecast path'});
 const region=poly([[[65.53,15.21],[65.98,15.30],[66.03,15.56],[65.71,15.63],[65.44,15.42],[65.53,15.21]]],{layer:'forecast-region',title:'Forecast affected region'});
 const candidates:CandidateVessel[]=noAis||noOil?[]:[
  {vessel:{mmsi:'419765432',name:'MV Sagar Nandini',type:'Oil/Chemical Tanker',flag:'IN'},rank:1,score:.82,confidence:partial?'LOW':'MEDIUM',distanceKm:2.1,temporalMatch:'Strong' as const,trajectoryMatch:'HIGH' as const,track:l([[64.91,14.92],[65.05,15.03],origin,[65.32,15.27]],{layer:'ais',mmsi:'419765432'}),position:p([65.32,15.27],{layer:'vessels',mmsi:'419765432',title:'MV Sagar Nandini'})},
  {vessel:{mmsi:'636019220',name:'MT Ocean Crest',type:'Crude Oil Tanker',flag:'LR'},rank:2,score:.71,confidence:'MEDIUM' as const,distanceKm:5.8,temporalMatch:'Moderate' as const,trajectoryMatch:'MEDIUM' as const,track:l([[64.7,15.1],[65,15.18],[65.21,15.34]],{layer:'ais',mmsi:'636019220'}),position:p([65.21,15.34],{layer:'vessels',mmsi:'636019220',title:'MT Ocean Crest'})},
  {vessel:{mmsi:'477551200',name:'MV Pelican',type:'Cargo',flag:'HK'},rank:3,score:.54,confidence:'LOW' as const,distanceKm:11.2,temporalMatch:'Weak' as const,trajectoryMatch:'LOW' as const,track:l([[65.12,14.7],[65.4,14.9],[65.7,15.05]],{layer:'ais',mmsi:'477551200'}),position:p([65.7,15.05],{layer:'vessels',mmsi:'477551200',title:'MV Pelican'})}
 ];
 const sarFootprint=poly([[[65.28,15.02],[65.61,15.02],[65.61,15.37],[65.28,15.37],[65.28,15.02]]],{layer:'sar-footprint',title:'Sentinel-1 SAR acquisition footprint',scene:'S1A_IW_GRDH_20260819'});
 const features:GeoCollection={type:'FeatureCollection',features:noOil?[]:[sarFootprint,spillPolygon,p(center,{layer:'centroid',title:'Spill centroid'}),...(noEnv?[]:[p(origin,{layer:'origin',title:'Probable origin'}),hindcast,forecast,region]),...candidates.flatMap(c=>[c.track,c.position]) ]};
 return {demo:true,scenario,incident:{id:'INC-001',eventTimestamp:'2026-08-19T04:20:00Z',location:center,region:'Arabian Sea',status:noOil?'NO_OIL':scenario==='processing'?'PROCESSING':scenario==='error'?'FAILED':'COMPLETE',detectionConfidence:noOil?null:.91,aisCoverage:noAis?'NONE':partial?'PARTIAL':'FULL',attributionStatus:noAis||noOil?'UNAVAILABLE':partial?'AVAILABLE_WITH_REDUCED_CONFIDENCE':'AVAILABLE'},scene:{id:'S1A_IW_GRDH_20260819',source:'Sentinel-1 SAR',acquisitionTime:'2026-08-19T04:12:00Z',qualityScore:.94,resolutionM:10},detection:{detected:!noOil,confidence:noOil?null:.91,modelVersion:'unet-sar-0.8.2',maskAvailable:!noOil},spill:noOil?null:{areaKm2:14.7,perimeterKm:19.4,centroid:center,orientationDeg:61,polygon:spillPolygon},environment:{weather:noEnv?'UNAVAILABLE':'GOOD',ocean:noEnv?'UNAVAILABLE':'LOW_QUALITY',windSpeedKn:noEnv?null:14,windDirectionDeg:noEnv?null:224,currentSpeedKn:noEnv?null:1.2,currentDirectionDeg:noEnv?null:201,timestamp:noEnv?null:'2026-08-19T04:00:00Z'},drift:{available:!noOil&&!noEnv,origin:!noOil&&!noEnv?p(origin,{layer:'origin',title:'Probable origin'}):null,originTime:!noOil&&!noEnv?'2026-08-18T18:20:00Z':null,uncertainty:noEnv?'UNAVAILABLE':'MEDIUM',hindcast:!noOil&&!noEnv?hindcast:null,forecast:!noOil&&!noEnv?forecast:null,affectedRegion:!noOil&&!noEnv?region:null},attribution:{status:noAis||noOil?'UNAVAILABLE':partial?'AVAILABLE_WITH_REDUCED_CONFIDENCE':'AVAILABLE',confidence:noAis||noOil?'UNAVAILABLE':partial?'LOW':'MEDIUM',candidates,evidence:candidates.map(c=>({candidateMmsi:c.vessel.mmsi,findings:[{label:`${c.distanceKm} km from probable origin`,status:'positive'},{label:`${c.temporalMatch} temporal match`,status:'positive'},{label:'Trajectory intersects drift corridor',status:'positive'},{label:'Heading compatible',status:'neutral'}],dimensions:[{name:'Distance',score:88},{name:'Temporal',score:82},{name:'Trajectory',score:79},{name:'Behaviour',score:57}]}))},confidence:{overall:noOil||noAis?'UNAVAILABLE':partial?'LOW':'MEDIUM',score:noOil||noAis?null:partial?62:78,dimensions:[{name:'Satellite Quality',score:94,availability:'GOOD'},{name:'Segmentation Quality',score:91,availability:'GOOD'},{name:'Environmental Data',score:noEnv?null:70,availability:noEnv?'UNAVAILABLE':'LOW_QUALITY'},{name:'AIS Coverage',score:noAis?null:partial?58:89,availability:noAis?'UNAVAILABLE':partial?'LOW_QUALITY':'GOOD'},{name:'Evidence Consistency',score:noAis?null:76,availability:noAis?'UNAVAILABLE':'GOOD'}]},pipeline:stages(scenario),map:features};
}
export const scenarios: {id:ScenarioId; label:string}[]=[{id:'full',label:'A · Full investigation'},{id:'partial-ais',label:'B · Partial AIS'},{id:'no-ais',label:'C · No AIS'},{id:'no-environment',label:'D · No environment'},{id:'no-oil',label:'E · No oil detected'},{id:'processing',label:'F · Processing'},{id:'error',label:'G · Pipeline error'}];
