import { Activity, AlertTriangle, ChevronRight, Database, Map as MapIcon, Radar, Ship, Waves, type LucideIcon } from 'lucide-react';
import { Link, NavLink } from 'react-router-dom';
import { scenarios } from '../mock/scenarios';
import { useUiStore } from '../store/uiStore';
import type { DashboardPayload, PipelineStage } from '../types/domain';
export const cls=(...s:(string|false|undefined)[])=>s.filter(Boolean).join(' ');
const navItems: [string,string,LucideIcon][]=[['/dashboard','Operations',Radar],['/incidents','Incidents',Database],['/create','New investigation',Activity],['/map','Analytical map',MapIcon],['/vessels','Vessel evidence',Ship],['/report','Report',ChevronRight]];
export function Shell({children}:{children:React.ReactNode}){const scenario=useUiStore(s=>s.scenario),set=useUiStore(s=>s.setScenario);return <div className="shell"><aside><Link className="brand" to="/"><Waves/> <span>OILSPILL<small>INTELLIGENCE</small></span></Link><nav>{navItems.map(([to,label,Icon])=><NavLink to={to} key={to}><Icon/>{label}</NavLink>)}</nav><div className="scenario"><label>DEMO SCENARIO</label><select value={scenario} onChange={e=>set(e.target.value as typeof scenario)}>{scenarios.map(s=><option value={s.id} key={s.id}>{s.label}</option>)}</select><p>All intelligence shown is synthetic.</p></div></aside><main><header><span className="eyebrow">MARITIME INTELLIGENCE / DEMONSTRATION</span><span className="live-dot">MOCK API ONLINE</span></header>{children}</main></div>}
export function Badge({children,tone='blue'}:{children:React.ReactNode;tone?:'blue'|'green'|'amber'|'red'|'muted'}){return <span className={`badge ${tone}`}>{children}</span>}
export function Metric({label,value,detail,accent=false}:{label:string;value:string;detail?:string;accent?:boolean}){return <article className={cls('metric',accent&&'accent')}><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</article>}
export function Pipeline({stages}:{stages:PipelineStage[]}){return <section className="pipeline panel"><div className="section-title">Investigation pipeline <Badge>SIMULATED</Badge></div><div className="pipeline-steps">{stages.map(x=><div key={x.id} className={`stage ${x.status}`}><i/ ><span>{x.label}</span><small>{x.status}</small></div>)}</div></section>}
export function EmptyState({title,children}:{title:string;children:React.ReactNode}){return <section className="empty panel"><AlertTriangle/><h2>{title}</h2><p>{children}</p></section>}
export function LayerControl(){const layers=useUiStore(s=>s.layers),toggle=useUiStore(s=>s.toggleLayer);return <div className="layer-control panel"><b>MAP LAYERS</b>{Object.entries(layers).map(([id,on])=><label key={id}><input type="checkbox" checked={on} onChange={()=>toggle(id)}/><span>{id.replaceAll('-',' ')}</span></label>)}</div>}
export function FeaturePanel({data}:{data:DashboardPayload}){const feature=useUiStore(s=>s.selectedFeature);return <aside className="feature-panel panel"><span className="eyebrow">CONTEXTUAL EVIDENCE</span><h3>{feature??'Select a map feature'}</h3>{feature?<p>Selected layer evidence is demo/simulated data. Detailed values remain traceable to this mock scenario.</p>:<p>Click a spill polygon, origin point, vessel, or trajectory to inspect it.</p>}<hr/><small>INCIDENT {data.incident.id}</small><p>{data.incident.region}<br/>{data.incident.location[1].toFixed(2)}° N / {data.incident.location[0].toFixed(2)}° E</p></aside>}
